### ISSUE TITLE
Unable to get level 15 or past even when using commands.

### ISSUE THREAD

**Issue by ferocioustoast** [rwtema/modjam2018#1]
Works fine in single player with the same pack, but in multiplayer I receive the following as soon I step on the nether fortress.

[21:41:36] [Server thread/INFO]: ferocioustoast7[/192.168.103.117:62006] logged in with entity id 91417 at (-271.61328881789325, 51.0, -139.5186327473449)
[21:41:36] [Server thread/INFO]: ferocioustoast7 joined the game
**[21:41:36] [Server thread/WARN]: Failed to handle packet for /192.168.103.117:62006
net.minecraft.util.ReportedException: Ticking player**
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
**Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V**
	at com.rwtema.monkmod.advancements.criteria.MonkRequirementStare.getStareEntity(MonkRequirementStare.java:36) ~[MonkRequirementStare.class:?]
	at com.rwtema.monkmod.abilities.MonkAbilityWitheringStare.tickServer(MonkAbilityWitheringStare.java:19) ~[MonkAbilityWitheringStare.class:?]
	at com.rwtema.monkmod.MonkManager.lambda$tick$0(MonkManager.java:60) ~[MonkManager.class:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146) ~[minecraft_server.1.12.2.jar:?]
	at com.rwtema.monkmod.MonkManager.tick(MonkManager.java:59) ~[MonkManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_570_MonkManager_tick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[21:41:36] [Server thread/INFO]: ferocioustoast7 lost connection: Internal server error
[21:41:36] [Server thread/INFO]: ferocioustoast7 left the game

**Comment by s2h** [comment]
I am new to modding, but as far as I understood:
in MonkRequirementStare.java:38 should fix the issue:
`new AxisAlignedBB(startPos.x, startPos.y, startPos.z, endPos.x, endPos.y, endPos.z)`
