### ISSUE TITLE
ConcurrentModificationException causes player to be kicked from server, can't re-join

### ISSUE THREAD

**Issue by CplPibald** [rwtema/modjam2018#11]
Using monk-mod-1.1 in a modpack on Forge 2655

Player (LV 19 monk) got kicked from MP server.  No crash, but the player can't re-join because the server throws the following exception on every login attempt.
```
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_151]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1471) ~[?:1.8.0_151]
        at com.rwtema.monkmod.abilities.MonkAbilityHealPotionEffects.tickServer(MonkAbilityHealPotionEffects.java:13) ~[MonkAbilityHealPotionEffects.class:?]
        at com.rwtema.monkmod.MonkManager.lambda$tick$0(MonkManager.java:72) ~[MonkManager.class:?]
        at com.google.common.collect.ImmutableSet$Indexed.forEach(ImmutableSet.java:392) ~[minecraft_server.1.12.2.jar:?]
        at com.rwtema.monkmod.MonkManager.tick(MonkManager.java:71) ~[MonkManager.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_427_MonkManager_tick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
```

**Comment by rwtema** [comment]
Ah, it looks to be an issue with someone having 2 potion effects. I only tested the code with 1 potion effect.
